### ISSUE TITLE
About matlab

### ISSUE THREAD

**Issue by coberC** [MDSplus/mdsplus#1]
os: window7x64sp1 simplechinese
matlab: 2013b
mdsplus: 6.1.62 x64 stable

There is no bug before update but after updata mdsplus from 2.3.0 to 6.1.62, two issues appears. 

Q1: can't read data from server by mdsvalue, list as follow

> > mdsopen('115.156.252.250::jtext',1036669) % ('server::tree',shot_number)
> > Error: File: mdsopen.m Line: 12 Column: 11
> > Arguments to IMPORT must either end with ".*" or else specify a fully
> > qualified class name: "MDSplus.Data" fails this test.
> > 
> > mdsconnect('115.156.252.250')
> > Error: File: mdsconnect.m Line: 13 Column: 12
> > Arguments to IMPORT must either end with ".*" or else specify a fully
> > qualified class name: "MDSplus.Connection" fails this test.

Q2: link problem at visual studio 2010 (c++project)
1>mdswrite.obj : error LNK2019: unresolved external symbol _MdsValue，it used in function "int __cdecl get_signal_length(char const *)" (?get_signal_length@@YAHPBD@Z)
1>mdswrite.obj : error LNK2019: unresolved external symbol _descr，it used in function "int __cdecl get_signal_length(char const *)" (?get_signal_length@@YAHPBD@Z)
1>mdswrite.obj : error LNK2019: unresolved external symbol _MdsDisconnect，it used in function _main
1>mdswrite.obj : error LNK2019: unresolved external symbol _MdsClose，it used in function _main
1>mdswrite.obj : error LNK2019: unresolved external symbol _MdsOpen，it used in function _main
1>mdswrite.obj : error LNK2019: unresolved external symbol _MdsConnect，it used in function _main
